version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - cd HomeFinderBackend  # Navigate to the Django backend directory
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests if any"
      # Add any build commands for your Django app
  post_build:
    commands:
      - echo "Creating deployment package"
      # Create the Elastic Beanstalk deployment package
      - zip -r ../deployment.zip .
      - cd ..
      - echo "Moving deployment package to root"

artifacts:
  files:
    - deployment.zip
  name: deployment